version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
  keycloak_pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    command: start-dev --db=postgres --db-url-host=keycloak_pg --db-username=keycloak --db-password=keycloak
    depends_on:
      - keycloak_pg
    ports:
      - 9000:8080
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_pg
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin@123
volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local