apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: openhmis
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        env:
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_ADMIN
                name: keycloaksecret
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: keycloaksecret
          - name: KEYCLOAK_POSTGRES_USER
            valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_POSTGRES_USER
                  name: keycloaksecret
          - name: KEYCLOAK_POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_POSTGRES_PASSWORD
                  name: keycloaksecret
        image: quay.io/keycloak/keycloak:19.0.2
        # command: ["start"]
        args: ["start --hostname-strict=false --http-enabled=true --hostname-strict-https=false --optimized --db-url-host=keycloakpg-service --db-username=$(KEYCLOAK_POSTGRES_USER) --db-password=$(KEYCLOAK_POSTGRES_PASSWORD)"]
        # args: [ "start-dev", "--db=postgres","--hostname-strict-https=false ","--hostname-strict=false","--http-enabled=true","--optimized","--db-url-host=keycloakpg-service","--db-username=$(KEYCLOAK_POSTGRES_USER)","--db-password=$(KEYCLOAK_POSTGRES_PASSWORD)"]
        resources:
          limits:
            memory: "528Mi"
            cpu: "900m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: openhmis
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
