apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-store
  namespace: openhmis
spec:
  selector:
    matchLabels:
      app: patient-store
  template:
    metadata:
      labels:
        app: patient-store
    spec:      
      imagePullSecrets:
        - name: jfrogcred
      containers:        
      - name: patient-store
        image: railtelhrit.jfrog.io/openhmis-docker/patient-store:latest
        env:
            - name: "PORT"
              value: "3000"
            - name: "MONGODB_HOST"
              value: "mongo-service"
            - name: "MONGODB_PORT"
              value: "27017"
            - name: "KAFKA_BROKER_ADDRESSLIST"
              value: "kafka-cluster-kafka-brokers.kafka:9092"
        resources:
          limits:
            memory: "228Mi"
            cpu: "500m"
            ephemeral-storage: 1Gi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: patient-store-service
  namespace: openhmis
spec:
  selector:
    app: patient-store
  ports:
  - port: 3000
    targetPort: 3000
